#!/usr/bin/env bash

THEME_NAME="palenight"

THEME_VARIANT="dark"
THEME_LAPTOP_MODE="false"
THEME_HEADER_BAR="dark"
THEME_PANEL="dark"

PALENIGHT_BACKGROUND="#292D3E"
PALENIGHT_FOREGROUND="#32364C"
PALENIGHT_DIVIDER="#4D5478"
PALENIGHT_COMMENT="#676E95"
PALENIGHT_ACCENT="#AB47BC"
PALENIGHT_RED="#FF5370"
PALENIGHT_ORANGE="#F78C6C"
PALENIGHT_YELLOW="#FFCB6B"
PALENIGHT_GREEN="#C3E88D"
PALENIGHT_BLUE="#82AAFF"
PALENIGHT_PURPLE="#C792EA"
PALENIGHT_TEXT="#EAEAEA"
