#!/usr/bin/env bash

THEME_VARIANT="dark"
THEME_LAPTOP_MODE="false"
THEME_HEADER_BAR="dark"
THEME_PANEL="dark"
THEME_STYLE="material"

THEME_COLOUR_BACKGROUND="#1A2026"
THEME_COLOUR_FOREGROUND="#242D35"
THEME_COLOUR_DIVIDER="#526170"
THEME_COLOUR_COMMENT="#526170"
THEME_COLOUR_DANGER="#F92D72"
THEME_COLOUR_MID_DANGER="#F692B2"
THEME_COLOUR_WARNING="#C269BC"
THEME_COLOUR_SUCCESS="#94CF95"
THEME_COLOUR_INFO="#7FE4D2"
THEME_COLOUR_DARK_INFO="#C792EA"
THEME_COLOUR_TEXT="#F4F5F2"
THEME_COLOUR_TEXT_HIGHLIGHT="#94CF95"

THEME_COLOUR_ACCENT_PRIMARY="#FB6396"
THEME_COLOUR_ACCENT_SECONDARY="#58D6BF"
THEME_COLOUR_ACCENT_TERTIARY="#FB6396"

THEME_COLOUR_UI_FOREGROUND_PRIMARY="$THEME_COLOUR_COMMENT"
THEME_COLOUR_UI_FOREGROUND_SECONDARY="$THEME_COLOUR_SUCCESS"
