#!/usr/bin/env bash

THEME_VARIANT="light"
THEME_LAPTOP_MODE="true"
THEME_HEADER_BAR="light"
THEME_PANEL="light"

THEME_COLOUR_BACKGROUND="#F5EBD0"
THEME_COLOUR_FOREGROUND="#F3E3BD"
THEME_COLOUR_DIVIDER="#3d4220"
THEME_COLOUR_COMMENT="#83A598"
THEME_COLOUR_DANGER="#fb4934"
THEME_COLOUR_MID_DANGER="#FE8019"
THEME_COLOUR_WARNING="#FABD2F"
THEME_COLOUR_SUCCESS="#B8BB26"
THEME_COLOUR_INFO="#979A1B"
THEME_COLOUR_DARK_INFO="#FF0000"
THEME_COLOUR_TEXT="#3c3836"
THEME_COLOUR_TEXT_HIGHLIGHT="#FF0000"
    
THEME_COLOUR_ACCENT_PRIMARY="#979A1B"
THEME_COLOUR_ACCENT_SECONDARY="#979A1B"
THEME_COLOUR_ACCENT_TERTIARY="#d3869b"
