#!/usr/bin/env bash

THEME_VARIANT="dark"
THEME_LAPTOP_MODE="false"
THEME_HEADER_BAR="dark"
THEME_PANEL="dark"
THEME_STYLE="material"

THEME_COLOUR_BACKGROUND="#263238"
THEME_COLOUR_FOREGROUND="#2B383E"
THEME_COLOUR_DIVIDER="#363E47"
THEME_COLOUR_COMMENT="#E53935"
THEME_COLOUR_DANGER="#E53935"
THEME_COLOUR_MID_DANGER="#FFB62C"
THEME_COLOUR_WARNING="#FFCB6B"
THEME_COLOUR_SUCCESS="#C3E88D"
THEME_COLOUR_INFO="#39ADB5"
THEME_COLOUR_DARK_INFO="#C792EA"
THEME_COLOUR_TEXT="#EFF1F5"
THEME_COLOUR_TEXT_HIGHLIGHT="#7C4DFF"

THEME_COLOUR_ACCENT_PRIMARY="$THEME_COLOUR_SUCCESS"
THEME_COLOUR_ACCENT_SECONDARY="$THEME_COLOUR_SUCCESS"
THEME_COLOUR_ACCENT_TERTIARY="$THEME_COLOUR_DARK_INFO"

THEME_COLOUR_UI_FOREGROUND_PRIMARY="$THEME_COLOUR_COMMENT"
THEME_COLOUR_UI_FOREGROUND_SECONDARY="$THEME_COLOUR_SUCCESS"
