#!/usr/bin/env bash

THEME_VARIANT="dark"
THEME_LAPTOP_MODE="false"
THEME_HEADER_BAR="dark"
THEME_PANEL="dark"
THEME_STYLE="material"

THEME_COLOUR_BACKGROUND="#292D3E"
THEME_COLOUR_FOREGROUND="#32364C"
THEME_COLOUR_DIVIDER="#4D5478"
THEME_COLOUR_COMMENT="#676E95"
THEME_COLOUR_DANGER="#FF5370"
THEME_COLOUR_MID_DANGER="#F78C6C"
THEME_COLOUR_WARNING="#FFCB6B"
THEME_COLOUR_SUCCESS="#C3E88D"
THEME_COLOUR_INFO="#82AAFF"
THEME_COLOUR_DARK_INFO="#C792EA"
THEME_COLOUR_TEXT="#EAEAEA"
THEME_COLOUR_TEXT_HIGHLIGHT="#FFCB6B"

THEME_COLOUR_ACCENT_PRIMARY="$THEME_COLOUR_SUCCESS"
THEME_COLOUR_ACCENT_SECONDARY="$THEME_COLOUR_SUCCESS"
THEME_COLOUR_ACCENT_TERTIARY="$THEME_COLOUR_DARK_INFO"

THEME_COLOUR_UI_FOREGROUND_PRIMARY="$THEME_COLOUR_COMMENT"
THEME_COLOUR_UI_FOREGROUND_SECONDARY="$THEME_COLOUR_SUCCESS"
