#!/usr/bin/env bash

THEME_VARIANT="dark"
THEME_LAPTOP_MODE="false"
THEME_HEADER_BAR="dark"
THEME_PANEL="dark"
THEME_STYLE="material"

THEME_COLOUR_BACKGROUND="#070D1B"
THEME_COLOUR_FOREGROUND="#1E3652"
THEME_COLOUR_DIVIDER="#5387DA"
THEME_COLOUR_COMMENT="#5DACEF"
THEME_COLOUR_DANGER="#B63031"
THEME_COLOUR_MID_DANGER="#1C0C16"
#THEME_COLOUR_WARNING="#8C6989"
THEME_COLOUR_WARNING="#3D478E"
THEME_COLOUR_SUCCESS="#5DADF6"
THEME_COLOUR_INFO="#8DFFFF"
THEME_COLOUR_DARK_INFO="#3262AE"
THEME_COLOUR_TEXT="#CDFDFF"
THEME_COLOUR_TEXT_HIGHLIGHT="#525BA0"

THEME_COLOUR_ACCENT_PRIMARY="$THEME_COLOUR_SUCCESS"
THEME_COLOUR_ACCENT_SECONDARY="$THEME_COLOUR_SUCCESS"
THEME_COLOUR_ACCENT_TERTIARY="$THEME_COLOUR_DARK_INFO"

THEME_COLOUR_UI_FOREGROUND_PRIMARY="$THEME_COLOUR_COMMENT"
THEME_COLOUR_UI_FOREGROUND_SECONDARY="$THEME_COLOUR_SUCCESS"
